version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: bankcards-db
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankcards
      POSTGRES_PASSWORD: bankcards
    ports:
      - "5432:5432"
    volumes:
      - bankcards_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankcards -d bankcards"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  bankcards_db_data:
